# NOTE: These data files need to be available:

# 1) GENERATED BY create_project_data.R:
# "../FinanceData/created_projects_datasets/DemoProject.Rdata"

##########################################################################################
# These are all the tables used in the .Rnw for the paper
##########################################################################################

rm(list=ls()) # Clean up the memory, if we want to rerun from scratch

source("helpers/lib_helpers.R", chdir=TRUE)
source("helpers/latex_code.R")
source("helpers/ff_industries_sic.R")
source("Paper_global_parameters.R")

# takes time to save and load, so we save only what is needed at the end.
initial_vars = ls(all = TRUE) 

##########################################################################################
# FILE LOCATIONS
##########################################################################################

project_data_location = "../FinanceData/created_projects_datasets/DemoProject.Rdata"
load(project_data_location)
# All the data filters are done in here - in case we want to change them for the paper
ISSUERS_DATA = BUYBACK_DATA # Just because filter_data_for_paper.R also uses it (should remove it from that file)
source("filter_data_for_paper.R")
rm("ISSUERS_DATA")

##########################################################################################
if (do.value.weight == 1){   
  value.weights_bb = BUYBACK_DATA$DATASET$CRSP$Market.Cap
} else {
  value.weights_bb = rep(1,length(BUYBACK_DATA$DATASET$CRSP$Market.Cap)) #  no value weighted calendar method
}

Risk_Factors_Monthly = BUYBACK_DATA$Risk_Factors_Monthly
Market_Monthly = BUYBACK_DATA$Market_Monthly
three_factor_model="(ri - RF) ~ Delta + SMB + HML"
five_factor_model = "(ri - RF) ~ Delta + SMB + HML + RMW + CMA"


##########################################################################################
# THIS IS WHERE THE VARIABLES FOR THE PAPER TABLES AND FIGURES ARE GENERATED
##########################################################################################

##########################################################################################
# Table I: Buybacks and RnD
# 

High_RnD_eventsBB = BUYBACK_DATA$RD > quantile(BUYBACK_DATA$RD, 1-quantile_simple)
Low_RnD_eventsBB  = BUYBACK_DATA$RD < quantile(BUYBACK_DATA$RD, quantile_simple)

# by RnD
useonly = High_RnD_eventsBB
tmp3f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model)$results
tmp5f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=five_factor_model)$results
IRATS_table_highRnD_BB = cbind(tmp3f,tmp5f)
colnames(IRATS_table_highRnD_BB)[1] <- "CAR 3F"
colnames(IRATS_table_highRnD_BB)[4] <- "CAR 5F"
tmp3f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model,value.weights = value.weights_bb[useonly])$results
tmp5f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,value.weights = value.weights_bb[useonly])$results
CAL_table_highRnD_BB = cbind(tmp3f, tmp5f)
colnames(CAL_table_highRnD_BB)[1] <- "CAL 3F"
colnames(CAL_table_highRnD_BB)[4] <- "CAL 5F"
rm("tmp3f","tmp5f")

useonly = Low_RnD_eventsBB
tmp3f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model)$results
tmp5f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=five_factor_model)$results
IRATS_table_lowRnD_BB = cbind(tmp3f,tmp5f)
colnames(IRATS_table_lowRnD_BB)[1] <- "CAR 3F"
colnames(IRATS_table_lowRnD_BB)[4] <- "CAR 5F"
tmp3f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model,value.weights = value.weights_bb[useonly])$results
tmp5f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,value.weights = value.weights_bb[useonly])$results
CAL_table_lowRnD_BB = cbind(tmp3f, tmp5f)
colnames(CAL_table_lowRnD_BB)[1] <- "CAL 3F"
colnames(CAL_table_lowRnD_BB)[4] <- "CAL 5F"
rm("tmp3f","tmp5f")

##########################################################################################
# Table II: Buyback and RnD: Low U-index (Overvalued) firms

company_subset_undervalued_bb = BUYBACK_DATA$Valuation_Index > quantile(BUYBACK_DATA$Valuation_Index, 1-quantile_simple)
company_subset_overvalued_bb = BUYBACK_DATA$Valuation_Index < quantile(BUYBACK_DATA$Valuation_Index,quantile_simple)

useonly = High_RnD_eventsBB & company_subset_overvalued_bb
tmp3f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model)$results
tmp5f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=five_factor_model)$results
IRATS_table_highRnD_Overvalued_BB = cbind(tmp3f,tmp5f)
colnames(IRATS_table_highRnD_Overvalued_BB)[1] <- "CAR 3F"
colnames(IRATS_table_highRnD_Overvalued_BB)[4] <- "CAR 5F"
tmp3f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model,value.weights = value.weights_bb[useonly])$results
tmp5f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,value.weights = value.weights_bb[useonly])$results
CAL_table_highRnD_Overvalued_BB = cbind(tmp3f, tmp5f)
colnames(CAL_table_highRnD_Overvalued_BB)[1] <- "CAL 3F"
colnames(CAL_table_highRnD_Overvalued_BB)[4] <- "CAL 5F"
rm("tmp3f","tmp5f")

useonly = Low_RnD_eventsBB & company_subset_overvalued_bb
tmp3f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model)$results
tmp5f = car_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=five_factor_model)$results
IRATS_table_lowRnD_Overvalued_BB = cbind(tmp3f,tmp5f)
colnames(IRATS_table_lowRnD_Overvalued_BB)[1] <- "CAR 3F"
colnames(IRATS_table_lowRnD_Overvalued_BB)[4] <- "CAR 5F"
tmp3f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,formula_used=three_factor_model,value.weights = value.weights_bb[useonly])$results
tmp5f = calendar_table(BUYBACK_DATA$DATASET$returns_by_event_monthly[,useonly], BUYBACK_DATA$DATASET$SDC$Event.Date[useonly], Risk_Factors_Monthly,value.weights = value.weights_bb[useonly])$results
CAL_table_lowRnD_Overvalued_BB = cbind(tmp3f, tmp5f)
colnames(CAL_table_lowRnD_Overvalued_BB)[1] <- "CAL 3F"
colnames(CAL_table_lowRnD_Overvalued_BB)[4] <- "CAL 5F"
rm("tmp3f","tmp5f")


########################################################################################################
# Now save the results of this file, which will be used in the .Rnw file to generate the final paper

save(list = setdiff(ls(all = TRUE),initial_vars), file = "data_for_paper.Rdata")
